name: Check if the commit is part of a merged PR

on:
  workflow_call:
    outputs:
      is_merged_pr:
        description: "Whether the current push came from a merged PR"
        value: ${{ jobs.check-pr.outputs.is_merged_pr }}
      pr_head_sha:
        description: "The head SHA of the merged PR"
        value: ${{ jobs.check-pr.outputs.pr_head_sha }}

jobs:
  check-pr:
    runs-on: ubuntu-latest
    outputs:
      is_merged_pr: ${{ steps.check-pr.outputs.result }}
      pr_head_sha: ${{ steps.check-pr.outputs.head_sha }}
    steps:
      - name: Check if this commit is from a merged PR
        id: check-pr
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            await (async () => {
              const commitSha = context.sha;
              const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: commitSha
              });
              const mergedPr = prs.find(pr => pr.merged_at !== null);
              const isMerged = Boolean(mergedPr);
              if (isMerged) {
                core.info(`Merged PR head SHA: ${mergedPr.head.sha}`);
                return { result: true, head_sha: mergedPr.head.sha };
              } else {
                return { result: false, head_sha: '' };
              }
            })();
